// docker-compose export. Compose networks are Linux bridges with a host
// gateway and NAT, so L2 semantics are approximate — each switch (or
// switch group) and each point-to-point link becomes a compose network.
// For faithful topology emulation prefer the containerlab export.
import type { Network } from '../engine/network';
import type { Device, NetInterface } from '../engine/device';
import { IpDevice } from '../engine/ipdevice';
import { SwitchDevice } from '../engine/switch';
import { cidrToString, ipToString, networkOf } from '../engine/ip';
import { nftExecCommands } from './containerlab';
import { sanitizeName } from './configs';

const IMAGE = 'nicolaka/netshoot';

interface Attachment {
  device: IpDevice;
  iface: NetInterface;
}

interface Segment {
  name: string;
  attachments: Attachment[];
  subnet: string | null;
}

// L2 segments: connected groups of switches plus every point-to-point link.
export function computeSegments(net: Network): Segment[] {
  const segments: Segment[] = [];
  const seenSwitches = new Set<string>();

  const attachmentsOf = (switches: Set<Device>): Attachment[] => {
    const out: Attachment[] = [];
    for (const sw of switches) {
      for (const port of sw.interfaces) {
        if (!port.link) continue;
        const other = port.link.other(port);
        if (other.device instanceof IpDevice) out.push({ device: other.device, iface: other });
      }
    }
    return out;
  };

  for (const d of net.devices.values()) {
    if (!(d instanceof SwitchDevice) || seenSwitches.has(d.id)) continue;
    const group = new Set<Device>();
    const queue: Device[] = [d];
    while (queue.length) {
      const sw = queue.pop()!;
      if (group.has(sw)) continue;
      group.add(sw);
      seenSwitches.add(sw.id);
      for (const port of sw.interfaces) {
        if (!port.link) continue;
        const other = port.link.other(port).device;
        if (other instanceof SwitchDevice && !group.has(other)) queue.push(other);
      }
    }
    segments.push({ name: sanitizeName(d.name), attachments: attachmentsOf(group), subnet: null });
  }

  for (const l of net.links.values()) {
    if (l.a.device instanceof IpDevice && l.b.device instanceof IpDevice) {
      segments.push({
        name: `p2p_${sanitizeName(l.a.device.name)}_${sanitizeName(l.b.device.name)}`,
        attachments: [
          { device: l.a.device, iface: l.a },
          { device: l.b.device, iface: l.b },
        ],
        subnet: null,
      });
    }
  }

  for (const seg of segments) {
    const withIp = seg.attachments.find((a) => a.iface.ip);
    if (withIp?.iface.ip) {
      const { addr, prefix } = withIp.iface.ip;
      seg.subnet = cidrToString(networkOf(addr, prefix), prefix);
    }
  }
  return segments;
}

export function composeYaml(net: Network): string {
  const segments = computeSegments(net);
  const lines: string[] = [
    '# Generated by NetSim.',
    '# NOTE: compose bridges add a host gateway + NAT, so this is an approximation',
    '# of the simulated L2 topology — use the containerlab export for fidelity.',
    'services:',
  ];
  const devices = [...net.devices.values()].filter((d): d is IpDevice => d instanceof IpDevice);
  for (const d of devices) {
    const name = sanitizeName(d.name);
    lines.push(`  ${name}:`);
    lines.push(`    image: ${IMAGE}`);
    lines.push(`    container_name: ${name}`);
    lines.push('    cap_add: [NET_ADMIN]');
    const cmds: string[] = [];
    for (const r of d.staticRoutes) {
      const dest = r.prefix === 0 ? 'default' : cidrToString(r.dest, r.prefix);
      const via = r.via !== null ? ` via ${ipToString(r.via)}` : '';
      cmds.push(`ip route replace ${dest}${via}`);
    }
    if (d.forwarding) cmds.push('sysctl -w net.ipv4.ip_forward=1');
    cmds.push(...nftExecCommands(d).map((c) => c.replace(/eth(\d+)/g, (_m, n) => `eth${Number(n) - 1}`)));
    cmds.push('sleep infinity');
    lines.push(`    command: sh -c "${cmds.join(' && ').replace(/"/g, '\\"')}"`);
    const segs = segments.filter((s) => s.attachments.some((a) => a.device === d));
    if (segs.length) {
      lines.push('    networks:');
      for (const s of segs) {
        const att = s.attachments.find((a) => a.device === d)!;
        if (att.iface.ip) {
          lines.push(`      ${s.name}:`);
          lines.push(`        ipv4_address: ${ipToString(att.iface.ip.addr)}`);
        } else {
          lines.push(`      ${s.name}: {}`);
        }
      }
    }
  }
  lines.push('networks:');
  for (const s of segments) {
    lines.push(`  ${s.name}:`);
    lines.push('    driver: bridge');
    if (s.subnet) {
      lines.push('    ipam:');
      lines.push('      config:');
      lines.push(`        - subnet: ${s.subnet}`);
    }
  }
  lines.push('');
  return lines.join('\n');
}
