// Exports the topology as a containerlab file: design in the browser, then
// `containerlab deploy -t netsim.clab.yml` runs it with real kernels.
// Mapping note: containerlab reserves eth0 for management, so simulated
// ethN becomes eth(N+1) inside the containers.
import type { Network } from '../engine/network';
import { IpDevice } from '../engine/ipdevice';
import { SwitchDevice } from '../engine/switch';
import { cidrToString, ipToString } from '../engine/ip';
import { filterRuleText, natRuleText } from '../engine/firewall-fmt';
import type { FilterHook, NatHook } from '../engine/firewall';
import { sanitizeName } from './configs';

const IMAGE = 'ghcr.io/hellt/network-multitool';

function clabIface(simName: string): string {
  const n = Number(simName.replace(/^eth/, ''));
  return `eth${Number.isInteger(n) ? n + 1 : simName}`;
}

const FILTER_PRIO: Record<FilterHook, string> = { input: '0', forward: '0', output: '0' };
const NAT_PRIO: Record<NatHook, string> = { prerouting: '-100', postrouting: '100' };

export function nftExecCommands(d: IpDevice): string[] {
  const fw = d.fw;
  const cmds: string[] = [];
  if (fw.tables.filter) {
    cmds.push('nft add table ip filter');
    for (const hook of ['input', 'forward', 'output'] as FilterHook[]) {
      const c = fw.filter[hook];
      if (!c.declared) continue;
      cmds.push(
        `nft 'add chain ip filter ${c.name} { type filter hook ${hook} priority ${FILTER_PRIO[hook]} ; policy ${c.policy} ; }'`,
      );
      for (const r of c.rules) cmds.push(`nft 'add rule ip filter ${c.name} ${filterRuleText(r)}'`);
    }
  }
  if (fw.tables.nat) {
    cmds.push('nft add table ip nat');
    for (const hook of ['prerouting', 'postrouting'] as NatHook[]) {
      const c = fw.nat[hook];
      if (!c.declared) continue;
      cmds.push(
        `nft 'add chain ip nat ${c.name} { type nat hook ${hook} priority ${NAT_PRIO[hook]} ; }'`,
      );
      for (const r of c.rules) cmds.push(`nft 'add rule ip nat ${c.name} ${natRuleText(r)}'`);
    }
  }
  // Interface names differ inside containerlab (ethN -> ethN+1).
  return cmds.map((c) => c.replace(/(iifname|oifname) "eth(\d+)"/g, (_m, kw, n) => `${kw} "eth${Number(n) + 1}"`));
}

export function containerlabYaml(net: Network, labName = 'netsim'): string {
  const lines: string[] = [
    '# Generated by NetSim — deploy with: containerlab deploy -t <this file>',
    '# NOTE: containerlab reserves eth0 for management; simulated ethN is eth(N+1) here.',
    '# DHCP/DNS/web services are exported separately in the configs bundle (dnsmasq.conf etc).',
    `name: ${sanitizeName(labName)}`,
    'topology:',
    '  nodes:',
  ];
  for (const d of net.devices.values()) {
    const name = sanitizeName(d.name);
    lines.push(`    ${name}:`);
    lines.push('      kind: linux');
    lines.push(`      image: ${IMAGE}`);
    const exec: string[] = [];
    if (d instanceof SwitchDevice) {
      exec.push('ip link add br0 type bridge', 'ip link set br0 up');
      for (const i of d.interfaces) {
        if (i.link) exec.push(`ip link set ${clabIface(i.name)} master br0`);
      }
    } else if (d instanceof IpDevice) {
      for (const i of d.interfaces) {
        if (i.ip) exec.push(`ip addr add ${cidrToString(i.ip.addr, i.ip.prefix)} dev ${clabIface(i.name)}`);
      }
      for (const r of d.staticRoutes) {
        const dest = r.prefix === 0 ? 'default' : cidrToString(r.dest, r.prefix);
        const via = r.via !== null ? ` via ${ipToString(r.via)}` : '';
        exec.push(`ip route replace ${dest}${via} dev ${clabIface(r.ifaceName)}`);
      }
      if (d.forwarding) exec.push('sysctl -w net.ipv4.ip_forward=1');
      exec.push(...nftExecCommands(d));
    }
    if (exec.length) {
      lines.push('      exec:');
      for (const c of exec) lines.push(`        - "${c.replace(/"/g, '\\"')}"`);
    }
  }
  lines.push('  links:');
  for (const l of net.links.values()) {
    lines.push(
      `    - endpoints: ["${sanitizeName(l.a.device.name)}:${clabIface(l.a.name)}", "${sanitizeName(l.b.device.name)}:${clabIface(l.b.name)}"]`,
    );
  }
  lines.push('');
  return lines.join('\n');
}
