// Self-contained, printable HTML documentation of the network design:
// inline diagram, device inventory, addressing, services, firewall rules.
import type { Network } from '../engine/network';
import { IpDevice } from '../engine/ipdevice';
import { SwitchDevice } from '../engine/switch';
import { cidrToString, ipToString } from '../engine/ip';
import { formatRoutes } from '../commands/ip-cmd';
import { listRuleset } from '../engine/firewall-fmt';
import { topologySvg, type NodePos } from './diagram';

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

export function networkReport(net: Network, positions: NodePos[], generatedAt: string): string {
  const devices = [...net.devices.values()];
  const parts: string[] = [];
  parts.push(`<!doctype html>
<html lang="en"><head><meta charset="utf-8"/>
<title>NetSim network report</title>
<style>
  body { font-family: Helvetica, Arial, sans-serif; color: #0f172a; max-width: 900px; margin: 32px auto; padding: 0 20px; }
  h1 { font-size: 24px; } h2 { font-size: 18px; margin-top: 32px; border-bottom: 2px solid #e2e8f0; padding-bottom: 6px; }
  h3 { font-size: 15px; margin-bottom: 6px; }
  .meta { color: #64748b; font-size: 12px; }
  table { border-collapse: collapse; width: 100%; font-size: 13px; margin: 8px 0 16px; }
  th, td { border: 1px solid #e2e8f0; padding: 6px 10px; text-align: left; vertical-align: top; }
  th { background: #f8fafc; }
  pre { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 10px 12px; font-size: 12px; overflow-x: auto; }
  .kind { text-transform: uppercase; font-size: 11px; color: #64748b; letter-spacing: 1px; }
  .diagram { margin: 16px 0; border: 1px solid #e2e8f0; border-radius: 8px; overflow: auto; }
  @media print { .diagram { border: none; } }
</style></head><body>`);
  parts.push('<h1>Network design report</h1>');
  parts.push(`<p class="meta">Generated by NetSim on ${esc(generatedAt)} · ${devices.length} devices · ${net.links.size} links</p>`);

  parts.push('<h2>Topology</h2>');
  parts.push(`<div class="diagram">${topologySvg(net, positions, '')}</div>`);

  parts.push('<h2>Device inventory</h2>');
  parts.push('<table><tr><th>Device</th><th>Kind</th><th>Addresses</th><th>Services</th></tr>');
  for (const d of devices) {
    const ips =
      d instanceof IpDevice
        ? d.interfaces
            .filter((i) => i.ip)
            .map((i) => `${i.name}: ${cidrToString(i.ip!.addr, i.ip!.prefix)}`)
            .join('<br/>')
        : '—';
    const services: string[] = [];
    if (d instanceof IpDevice) {
      if (d.forwarding) services.push('IP forwarding');
      if (d.fw.active()) services.push('firewall');
      if (d.dhcpServer?.enabled) services.push('DHCP server');
      if (d.dnsServer?.enabled) services.push('DNS server');
      if (d.httpServer?.enabled) services.push(`web (:${d.httpServer.port})`);
      if (d.services.tcp.size) services.push(`tcp ports ${[...d.services.tcp].join(',')}`);
      if (d.services.udp.size) services.push(`udp ports ${[...d.services.udp].join(',')}`);
      if (d.nameserver !== null) services.push(`resolver → ${ipToString(d.nameserver)}`);
    }
    parts.push(
      `<tr><td><strong>${esc(d.name)}</strong></td><td class="kind">${d.kind}</td><td><code>${ips || '—'}</code></td><td>${services.map(esc).join('; ') || '—'}</td></tr>`,
    );
  }
  parts.push('</table>');

  parts.push('<h2>Cabling</h2>');
  parts.push('<table><tr><th>From</th><th>Interface</th><th>To</th><th>Interface</th></tr>');
  for (const l of net.links.values()) {
    parts.push(
      `<tr><td>${esc(l.a.device.name)}</td><td><code>${esc(l.a.name)}</code></td><td>${esc(l.b.device.name)}</td><td><code>${esc(l.b.name)}</code></td></tr>`,
    );
  }
  parts.push('</table>');

  for (const d of devices) {
    if (!(d instanceof IpDevice)) continue;
    const hasRoutes = d.routes().length > 0;
    const hasFw = d.fw.active();
    const dnsRecords = d.dnsServer?.enabled ? [...d.dnsServer.records.entries()] : [];
    if (!hasRoutes && !hasFw && !dnsRecords.length && !d.dhcpServer?.enabled) continue;
    parts.push(`<h2>${esc(d.name)} <span class="kind">${d.kind}</span></h2>`);
    if (hasRoutes) {
      parts.push('<h3>Routing table</h3>');
      parts.push(`<pre>${esc(formatRoutes(d))}</pre>`);
    }
    if (d.dhcpServer?.enabled) {
      const c = d.dhcpServer;
      parts.push('<h3>DHCP server</h3>');
      parts.push(
        `<pre>range ${ipToString(c.rangeStart)} – ${ipToString(c.rangeEnd)}\nrouter ${c.router !== null ? ipToString(c.router) : '—'}\ndns    ${c.dns !== null ? ipToString(c.dns) : '—'}</pre>`,
      );
    }
    if (dnsRecords.length) {
      parts.push('<h3>DNS records</h3>');
      parts.push(`<pre>${esc(dnsRecords.map(([n, a]) => `${ipToString(a)}  ${n}`).join('\n'))}</pre>`);
    }
    if (hasFw) {
      parts.push('<h3>Firewall ruleset (nftables)</h3>');
      parts.push(`<pre>${esc(listRuleset(d.fw))}</pre>`);
    }
  }

  for (const d of devices) {
    if (d instanceof SwitchDevice && d.macTable.size) {
      parts.push(`<h2>${esc(d.name)} <span class="kind">switch</span></h2>`);
      parts.push('<h3>MAC address table (live)</h3>');
      parts.push(
        `<pre>${esc([...d.macTable.entries()].map(([mac, p]) => `${mac}  ${p.name}`).join('\n'))}</pre>`,
      );
    }
  }

  parts.push('</body></html>');
  return parts.join('\n');
}
